# Generated by Django 4.2.7 on 2023-11-22 15:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(default='default_profile_pic.jpg', upload_to='profile_pics/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InstitutionalProfile',
            fields=[
                ('profile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='profiles.profile')),
                ('name', models.CharField(max_length=200)),
                ('institution_type', models.CharField(blank=True, max_length=100)),
                ('contact_info', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('logo', models.ImageField(default='default_logo.jpg', upload_to='institution_logos/')),
                ('website', models.URLField(blank=True)),
                ('industry', models.CharField(blank=True, max_length=100)),
                ('size', models.CharField(blank=True, max_length=100)),
            ],
            bases=('profiles.profile',),
        ),
        migrations.CreateModel(
            name='PersonalProfile',
            fields=[
                ('profile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='profiles.profile')),
                ('contact', models.CharField(max_length=100)),
                ('resume', models.FileField(blank=True, null=True, upload_to='resumes/')),
                ('bio', models.TextField(blank=True)),
                ('skills', models.TextField(blank=True)),
                ('education', models.TextField(blank=True)),
                ('work_experience', models.TextField(blank=True)),
            ],
            bases=('profiles.profile',),
        ),
        migrations.CreateModel(
            name='ProfessionalProfile',
            fields=[
                ('personalprofile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='profiles.personalprofile')),
                ('professional_title', models.CharField(blank=True, max_length=100)),
                ('professional_bio', models.TextField(blank=True)),
                ('linkedin_profile', models.URLField(blank=True)),
                ('publications_portfolio', models.URLField(blank=True)),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='profiles.institutionalprofile')),
            ],
            bases=('profiles.personalprofile',),
        ),
    ]
