# Generated by Django 4.2.7 on 2023-11-22 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalprofile',
            name='profile_ptr',
        ),
        migrations.RemoveField(
            model_name='professionalprofile',
            name='institution',
        ),
        migrations.RemoveField(
            model_name='professionalprofile',
            name='personalprofile_ptr',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='InstitutionalProfile',
        ),
        migrations.DeleteModel(
            name='PersonalProfile',
        ),
        migrations.DeleteModel(
            name='ProfessionalProfile',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
